version: 2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: src/Tesseract.Api
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: src/Tesseract.Api
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t francolianza/tesseract-api:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push francolianza/tesseract-api:latest
          working_directory: src/Tesseract.Api